test_data = {
    "housing_type": "Новостройка",
    "district": "Канавинский",
    "rooms": 3,
    "is_studio": "Нет",
    "total_area": 62.2,
    "living_area": 29.2,
    "kitchen_area": 9.9,
    "floor": 10,
    "num_floors": 25,
    "bathrooms_type": "Раздельный",
    "num_loggia": 1,
    "num_balcony": 0,
    "kitchen_and_living": "Да",
    "condition": "Предчистовая",
    "ceiling_height": 3.0,
    "nearest_metro_st": "Чкаловская",
    "minutes_to_metro": 1,
    "num_freight_lift": 1,
    "num_passenger_lift": 1,
    "parking_type": "Подземная",
    "building_type": "Монолитно-кирпичный",
    "furniture": "Нет",
    "deal_type": "Долевое участие (214-ФЗ)",
    "house_completion_year": 2027,
    "first_floor_is_com": "Да",
    "playground": "Да",
    "floor_ratio": 10 / 25,
    "living_ratio": 29.2 / 62.2,
}

var = {
    "data": {
        "housing_type": "Новостройка",
        "district": "Канавинский",
        "rooms": 3,
        "is_studio": "Нет",
        "total_area": 62.2,
        "living_area": 29.2,
        "kitchen_area": 9.9,
        "floor": 10,
        "num_floors": 25,
        "bathrooms_type": "Раздельный",
        "num_loggia": 1,
        "num_balcony": 0,
        "kitchen_and_living": "Да",
        "condition": "Предчистовая",
        "ceiling_height": 3.0,
        "nearest_metro_st": "Чкаловская",
        "minutes_to_metro": 1,
        "num_freight_lift": 1,
        "num_passenger_lift": 1,
        "parking_type": "Подземная",
        "building_type": "Монолитно-кирпичный",
        "furniture": "Нет",
        "deal_type": "Долевое участие (214-ФЗ)",
        "house_completion_year": 2027,
        "first_floor_is_com": "Да",
        "playground": "Да",
        "floor_ratio": 1,
        "living_ratio": 1,
    },
    "user": {"email": "user@example.com", "password": "string"},
}

{"email": "user1@mail.com", "password": "1234567890"}
